// Layla, la gata atigrada de la tienda · generado con tools/arte/layla.py (python3)
export const LAYLA_PAL: Record<string, string> = {"k": "#120c08", "o": "#e8913a", "O": "#b8621e", "d": "#7a3a12", "W": "#f4ece0", "w": "#d8c8b0", "G": "#7ad84a", "g": "#2a5a1a", "p": "#f0a0a8", "n": "#6a4a2a", "N": "#4a3020", "y": "#e8c15a", "Y": "#a87a2a", "r": "#a8323a"};
export const LAYLA_ROWS: string[] = [
  '....kkkkkkk......kkkkkkk......',
  '...koooooook....koooooook.....',
  '....koooook......koooook......',
  '....koopookkkkkkkkoopook......',
  '.....kppokooooooookoppk.......',
  '.....koooooOoOOoOoooook.......',
  '......koooooOOOOoooook........',
  '......kooooooooooooook........',
  '.....kooooooooooooooook.......',
  '....kOOooWkGooooWkGooOOk......',
  '.....koooGkGooooGkGoook.......',
  '....kOooooooWWWWooooooOk......',
  '...kwwooooWWWppWWWoooowwk.....',
  '....kkwoooWWWkkWWWooowkk......',
  '...kwwkkooWWkWWkWWookkwwk.....',
  '....kk..koooWWWWoook..kk......',
  '......kkrrrrrrrrrrrrkk........',
  '.....kOOkooooyyooookOOk.kkk...',
  '.....kOOooooyYYyooooOOkkWWok..',
  '......kooooWWyyWWooook.koooOk.',
  '.....kOOooWWWWWWWWooOOkkoooOk.',
  '.....kOOooWWWWWWWWooOOk.kOOOok',
  '.....kooooWWWWWWWWooook..koook',
  '.....kOOooWWWWWWWWooOOk..koook',
  '.....kOOoWWWWWWWWWWoOOk..kOOOk',
  '.....kooooWWWWWWWWooook.koOOOk',
  '......koooWWWWWWWWoook.kkoook.',
  '......koooWWWWWWWWoookkOOoook.',
  '.......kooWWWWWWWWookooOOOkk..',
  '........kWWWWWWWWWWkkooOOOk...',
  '........kWWWWWWWWWWkkoookk....',
  '........kWwWWkkWwWWk.kkk......',
];
