// Layla, la gata atigrada de la tienda · generado con tools/arte/layla.py (python3)
export const LAYLA_PAL: Record<string, string> = {"k": "#100e0c", "o": "#8c7f6c", "O": "#3e352c", "d": "#2a241e", "W": "#eee8de", "w": "#c4baac", "q": "#a89c88", "G": "#8ca89a", "g": "#2a3a34", "p": "#a8746a", "n": "#6a4a2a", "N": "#4a3020", "y": "#e8c15a", "Y": "#a87a2a", "r": "#a8323a"};
export const LAYLA_ROWS: string[] = [
  '....kkkkkkk......kkkkkkk......',
  '...koooooook....koooooook.....',
  '....koooook......koooook......',
  '....koopookkkkkkkkoopook......',
  '.....kppokooOooOookoppk.......',
  '.....koooooOoOOoOoooook.......',
  '......koooooOOOOoooook........',
  '......kooooooOOooooook........',
  '.....koooWGGooooWGGoook.......',
  '....kOOooGgGooooGgGooOOk......',
  '...kOkoooGgGooooGgGoookOk.....',
  '....kOOOooooWWWWooooOOOk......',
  '...kwwOoooWWWppWWWoooOwwk.....',
  '....kkwoooWWWkkWWWooowkk......',
  '...kwwkkooWWkWWkWWookkwwk.....',
  '....kk..koooWWWWoook..kk......',
  '.......krrrrrrrrrrrrk.........',
  '........kqoooyyoooqk....kkk...',
  '.......koqooyYYyooqok..kOOok..',
  '......kOOqoWWyyWWoqOOk.koooOk.',
  '......kooqWWWWWWWWqook.koooOk.',
  '.....koooqWWWWWWWWqoook.kOOOok',
  '.....kOOOqWWWWWWWWqOOOk..koook',
  '.....koooqWWWWWWWWqoook..koook',
  '.....koooWWWWWWWWWWoook..kOOOk',
  '.....kOOOqWWWWWWWWqOOOk.koOOOk',
  '......kooqWWWWWWWWqook.kkoook.',
  '......kooqWWWWWWWWqookkOOoook.',
  '.......koooooWWoooookooOOOkk..',
  '........kOooOWWOooOkkooOOOk...',
  '........kooooWWooookkoookk....',
  '........kWWWWkkWWWWk.kkk......',
];
